#docker-compose.yml
version: '3'

services:
  main:
    image: redis:7.2
    hostname: redis
    ports:
      - 6379:6379
    networks:
      - redis-replication

  replica:
    image: redis:7.2
    hostname: redis-replica
    deploy:
      replicas: 3
    command: redis-server --slaveof redis 6379
    depends_on:
      - main
    networks:
      - redis-replication

  server:
    image: lunatrn/node-redis:latest
    hostname: server
    ports:
      - 8080:8080
    depends_on:
      - main
      - replica
    networks:
      - redis-replication
    environment:
      - REDIS_URL=redis://redis:6379
      - REDIS_REPLICAS_URL=redis://redis-replica:6379

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - redis-replication

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3030:3000
    networks:
      - redis-replication

  frontend:
    image: lunatrn/redis-react:latest
    ports:
      - 80:80
    networks:
      - redis-replication

networks:
  redis-replication:
    driver: bridge
