FROM node:latest as build

WORKDIR /usr/src/app

COPY package.json .
COPY yarn.lock .
COPY public/ ./public
COPY src/ ./src

RUN yarn install
RUN yarn build

FROM nginx:alpine

COPY --from=build /usr/src/app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
