global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node-redis'
    static_configs:
      - targets: ['node-redis:8080']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
